name: README contributors section

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - .all-contributorsrc
      - .github/workflows/allcontributors.yml
      - README*.md

jobs:
  regenerate:
    runs-on: ubuntu-latest
    name: Regenerate
    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.AUTOCOMMITS_DEPLOY_KEY }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - run: bun all-contributors generate

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ðŸ‘¥ Update contributors list
          file_pattern: README*.md
