name: Bundle size

on:
  workflow_call:
    inputs: {}
    secrets:
      DEV_DEPLOYMENTS_SSH_PRIVATE_KEY:
        required: true

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 'true'

permissions:
  contents: read
  actions: read

jobs:
  compare:
    runs-on: ubuntu-latest
    name: Compare
    needs: build

    permissions:
      pull-requests: write

    steps:
      - name: Download stats.json files
        uses: actions/download-artifact@v7

      - name: Compare bundle size
        id: comparison
        uses: wojtekmaj/vite-compare-bundle-size@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/stats.json
          base-stats-json-path: ./base-stats/stats.json
          describe-assets: changed-only

      - name: Get PR labels
        id: pr
        run: echo labels="$(
          gh pr -R ${{ github.repository }}
          view ${{ github.event.pull_request.number }}
          --json labels
          --jq '.labels[].name'
          )" >> $GITHUB_OUTPUT

      # TODO figure out if the action has outputs, use those instead
      - if: ${{ !contains(steps.pr.outputs.labels, 'bypass:bundlesize') }}
        name: Enforce less than 5% increase
        run: |
          gzip_sum_base=$(jq '[.[].gzipSize] | add' base-stats/stats.json)
          gzip_sum_head=$(jq '[.[].gzipSize] | add' head-stats/stats.json)
          gzip_diff_abs=$((gzip_sum_head - gzip_sum_base))
          gzip_diff_perc=$(echo "scale=2; $gzip_diff_abs / $gzip_sum_base * 100" | bc)
          echo "Base branch gzip size: $gzip_sum_base bytes"
          echo "Head branch gzip size: $gzip_sum_head bytes"
          echo "Gzip size difference: $gzip_diff_abs bytes ($gzip_diff_perc%)"
          if (( $(echo "$gzip_diff_perc > 5" | bc -l) )); then
            echo "Bundle size increased by more than 5%!"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { name: head, ref: '${{ github.event.pull_request.head.ref }}' }
          - { name: base, ref: '${{ github.base_ref }}' }
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.ref }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - run: bun install

      - run: bun run build
        if: matrix.name == 'head'
        env:
          BUNDLE_ANALYZER: json,static
      - run: bun run build
        if: matrix.name != 'head'
        env:
          BUNDLE_ANALYZER: json

      - name: Upload stats.json
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}-stats
          path: ./public/stats.json

      # dev-deploy.yml expects a index.html file
      - if: matrix.name == 'head'
        run: mkdir -p bundlestats; mv public/stats.html bundlestats/index.html
      - if: matrix.name == 'head'
        name: Upload bundle analysis site
        uses: actions/upload-artifact@v6
        with:
          path: ./bundlestats
          name: ${{ matrix.name }}-bundle-analysis

  deploy-breakdown:
    name: Breakdown site
    needs: build
    uses: ./.github/workflows/dev-deploy.yml
    secrets: inherit
    with: 
      artifact: head-bundle-analysis
      subdomain: pr-${{ github.event.pull_request.number }}-reports
      path: /bundlesize
      environment: "#${{ github.event.pull_request.number }}: Bundle breakdown"

          
