name: Update Changelog

on:
  workflow_dispatch:
  schedule:
    # Every end of of the month at 00:00 UTC
    - cron: '0 0 28 * *'
    - cron: '0 0 30 * *'
    - cron: '0 0 31 * *'
    # Every week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  push:
    branches: [main]
    paths: [.github/workflows/changelog.yml, scripts/generate-changelog.js, CHANGELOG.md]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Fetch all history for accurate changelog generation
          fetch-depth: 0
          ssh-key: ${{ secrets.AUTOCOMMITS_DEPLOY_KEY }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Update CHANGELOG.md
        run: bun run scripts/generate-changelog.js 2024-01-01

      - name: Format CHANGELOG.md
        run: bun run prettier --write CHANGELOG.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: üìù Update CHANGELOG.md
          file_pattern: CHANGELOG.md
