name: Translations

on:
  push:
    branches-ignore:
      - renovate/*
      - dependabot/*
  workflow_dispatch:
    inputs:
      build-image:
        description: Build the i18n Docker image
        required: false
        type: boolean
        default: false

jobs:
  build-image:
    name: Build i18n Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - if: github.event.inputs.build-image
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .github/workflows
          file: .github/workflows/i18n.Dockerfile
          push: true
          tags: ghcr.io/cigaleapp/cigale/i18n:latest

  refresh:
    needs: [build-image]
    name: Refresh .po files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: ghcr.io/cigaleapp/cigale/i18n:latest
    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.AUTOCOMMITS_DEPLOY_KEY }}
      - name: Make working dir git-safe (we're root in a container)
        run: git config --global --add safe.directory $(pwd)
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run wuchale to update .po files
        run: bun wuchale --clean
      - name: Setup .po diffing
        run: git config diff.podiff.command "$command"
        env:
          command: podiff
            -D -u
            -D '-I PO-Revision-Date'
            -D '-I Language-Team'
            -D '-I MIME-Version'
            -L
      - name: Check for changes
        id: status
        run: |
          git diff | grep -v '^index ' || echo "No changes"
          git diff | grep -q -v '^index ' && echo "Changes detected" || echo "No changes"
          # for some reason, empty diff with podiff still returns status 1, and "index ....." lines
          # so we don't use --exit-code, but we | grep -v ^index instead
          echo dirty=$(git diff | grep -q -v '^index ' && echo "true" || echo "false") >> $GITHUB_OUTPUT
      - if: steps.status.outputs.dirty == 'true'
        name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: ğŸŒ Refresh translation files
          commit_options: --no-verify
          file_pattern: src/locales/*.po
